[Unit]
RequiresMountsFor=/mnt/usb /mnt/paperless

[Service]
ExecStartPre=/usr/bin/mountpoint -q /mnt/usb
ExecStartPre=/usr/bin/findmnt -rn -t cifs --mountpoint /mnt/paperless
ExecStart=
ExecStart=/usr/bin/docker compose up -d --wait --wait-timeout 180
TimeoutStartSec=240
