---
galaxy_info:
  author: karsten
  description: Docker service restore role
  company: Personal
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - restore
    - docker

dependencies:
  - backup_utils
