---
- name: Restore Paperless-ngx from latest available backup (local, NAS, or OneDrive)
  hosts: localhost
  become: yes

  vars_prompt:
    - name: confirm_restore
      prompt: |
        WARNING: This will DELETE your existing ~/paperless directory and replace it with the latest backup.
        Type YES to proceed:
      private: no

  pre_tasks:
    - name: Abort if not confirmed
      fail:
        msg: "Restore cancelled."
      when: confirm_restore != "YES"

  vars:
    paperless_dir: /home/karsten/paperless
    backup_dir: /home/karsten/paperless_backups
    nas_backup_dir: /mnt/paperless/backup
    rclone_remote: "onedrive:paperless_backups"

  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: karsten
        group: karsten
        mode: '0755'

    - name: Stop Paperless-ngx containers
      become_user: karsten
      shell: docker-compose down
      args:
        chdir: "{{ paperless_dir }}"

    # --- Find latest local backup ---
    - name: Find latest local backup
      become_user: karsten
      shell: |
        ls -1t {{ backup_dir }}/paperless_backup_*.tar.gz 2>/dev/null | head -n 1
      register: local_backup
      changed_when: false

    # --- Find latest NAS backup ---
    - name: Find latest NAS backup
      become_user: karsten
      shell: |
        ls -1t {{ nas_backup_dir }}/paperless_backup_*.tar.gz 2>/dev/null | head -n 1
      register: nas_backup
      changed_when: false

    # --- Find latest OneDrive backup ---
    - name: Find latest OneDrive backup
      become_user: karsten
      shell: |
        rclone ls "{{ rclone_remote }}" | awk '{print $2}' | grep '^paperless_backup_.*\.tar\.gz$' | sort | tail -n 1
      register: onedrive_backup
      changed_when: false

    # --- Set restore source and file ---
    - name: Set restore source and file (local > NAS > OneDrive)
      set_fact:
        restore_source: >-
          {% if local_backup.stdout != "" %}
            local
          {% elif nas_backup.stdout != "" %}
            nas
          {% elif onedrive_backup.stdout != "" %}
            onedrive
          {% else %}
            none
          {% endif %}
        restore_file: >-
          {% if local_backup.stdout != "" %}
            {{ local_backup.stdout }}
          {% elif nas_backup.stdout != "" %}
            {{ nas_backup.stdout }}
          {% elif onedrive_backup.stdout != "" %}
            {{ onedrive_backup.stdout }}
          {% else %}
            ""
          {% endif %}

    - name: Fail if no backup found anywhere
      fail:
        msg: "No backups found in local, NAS, or OneDrive!"
      when: restore_source == "none"

    # --- If restoring from OneDrive, download it to backup_dir ---
    - name: Download latest backup from OneDrive if needed
      become_user: karsten
      shell: |
        rclone copy "{{ rclone_remote }}/{{ restore_file }}" "{{ backup_dir }}/"
      when: restore_source == "onedrive"
      args:
        executable: /bin/bash

    # --- If restoring from NAS, copy it to backup_dir ---
    - name: Copy latest backup from NAS if needed
      become_user: karsten
      shell: |
        cp "{{ restore_file }}" "{{ backup_dir }}/"
      when: restore_source == "nas"
      args:
        executable: /bin/bash

    # --- Remove existing paperless directory ---
    - name: Remove existing paperless directory
      file:
        path: "{{ paperless_dir }}"
        state: absent

    - name: Recreate paperless directory
      become_user: karsten
      file:
        path: "{{ paperless_dir }}"
        state: directory
        mode: '0755'

    # --- Extract backup archive into ~/paperless ---
    - name: Extract backup archive into ~/jellyfin
      become_user: karsten
      unarchive:
        src: "{{ backup_dir }}/{{ latest_backup.stdout }}"
        dest: "/home/karsten"
        remote_src: no
        extra_opts:
          - --overwrite
          - --no-same-owner
          - --no-same-permissions
          
    - name: Start Paperless-ngx containers
      become_user: karsten
      shell: docker-compose up -d
      args:
        chdir: "{{ paperless_dir }}"
