---
# Main backup tasks for Docker services

# Pre-flight checks
- name: Verify service directory exists
  stat:
    path: "{{ service_dir }}"
  register: service_dir_stat
  failed_when: not service_dir_stat.stat.exists

- name: Verify docker-compose file exists
  stat:
    path: "{{ compose_file }}"
  register: compose_file_stat
  failed_when: not compose_file_stat.stat.exists

- name: Ensure backup directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: karsten
    group: karsten
    mode: '0755'
  loop:
    - "{{ backup_dir }}"
#    - "{{ nas_backup_dir }}"

# Main backup process with error handling
- block:
    - name: Stop {{ service_name }} containers
      block:
        - name: Stop containers using Docker Compose V2 module
          community.docker.docker_compose_v2:
            project_src: "{{ service_dir }}"
            state: absent
          register: stop_result
      rescue:
        - name: Stop containers using shell command (fallback)
          shell: |
            if command -v docker >/dev/null 2>&1; then
              if docker compose version >/dev/null 2>&1; then
                docker compose down
              elif docker-compose --version >/dev/null 2>&1; then
                docker-compose down
              else
                echo "No Docker Compose found"
                exit 1
              fi
            else
              echo "Docker not found"
              exit 1
            fi
          args:
            chdir: "{{ service_dir }}"
          register: stop_result

    - name: Check for Docker volumes related to {{ service_name }}
      shell: docker volume ls --format "{{ '{{' }}.Name{{ '}}' }}" | grep "^{{ service_name }}_"
      register: volumes_result
      failed_when: false

    - name: Filter volumes for this service
      set_fact:
        service_volumes: "{{ volumes_result.stdout_lines if volumes_result.rc == 0 else [] }}"

    - name: Create archive (no volumes case)
      community.general.archive:
        path: "{{ service_dir }}"
        dest: "{{ backup_dir }}/{{ backup_file }}"
        format: gz
        owner: karsten
        group: karsten
        mode: '0644'
      when: service_volumes | length == 0

    - name: Create temporary directory for volume backups
      tempfile:
        state: directory
        suffix: _{{ service_name }}_backup
      register: temp_backup_dir
      when: service_volumes | length > 0

    - name: Backup Docker volumes using Ansible Docker module
      community.docker.docker_container:
        name: "backup_{{ service_name }}_{{ item }}"
        image: alpine:latest
        state: started
        detach: false
        cleanup: true
        auto_remove: true
        volumes:
          - "{{ item }}:/volume:ro"
          - "{{ temp_backup_dir.path }}:/backup"
        command: tar czf /backup/{{ item }}.tar.gz -C /volume .
      loop: "{{ service_volumes }}"
      when: service_volumes | length > 0

    - name: Create combined archive with volumes
      shell: |
        cd "{{ service_dir | dirname }}"
        tar czf "{{ backup_dir }}/{{ backup_file }}" "{{ service_name }}"
        cd {{ temp_backup_dir.path }}
        if [ -n "$(ls -A *.tar.gz 2>/dev/null)" ]; then
          # Extract individual volume backups and add to main archive
          for volume_backup in *.tar.gz; do
            volume_name=$(basename "$volume_backup" .tar.gz)
            mkdir -p "volumes/$volume_name"
            tar xzf "$volume_backup" -C "volumes/$volume_name"
          done
          # Add volumes directory to the main archive
          tar --append -f "{{ backup_dir }}/{{ backup_file }}" volumes/ || tar czf "{{ backup_dir }}/{{ backup_file }}.new" -C "{{ service_dir | dirname }}" "{{ service_name }}" -C "{{ temp_backup_dir.path }}" volumes && mv "{{ backup_dir }}/{{ backup_file }}.new" "{{ backup_dir }}/{{ backup_file }}"
        fi
      when: service_volumes | length > 0

    - name: Clean up temporary backup directory
      file:
        path: "{{ temp_backup_dir.path }}"
        state: absent
      when: service_volumes | length > 0

    - name: Verify backup file was created
      stat:
        path: "{{ backup_dir }}/{{ backup_file }}"
      register: backup_stat
      failed_when: not backup_stat.stat.exists or backup_stat.stat.size < 1024

    - name: Upload Backup
      include_tasks: upload_backup.yml

    - name: Cleanup backups
      include_tasks: cleanup_backups.yml

  rescue:
    - name: Log backup failure
      debug:
        msg: "Backup failed: {{ ansible_failed_result.msg | default('Unknown error') }}"
      
    - name: Fail the playbook
      fail:
        msg: "Backup process failed, but containers will be restarted"

  always:
    - name: Start {{ service_name }} containers
      block:
        - name: Start containers using Docker Compose V2 module
          community.docker.docker_compose_v2:
            project_src: "{{ service_dir }}"
            state: present
          register: start_result
      rescue:
        - name: Start containers using shell command (fallback)
          shell: |
            if command -v docker >/dev/null 2>&1; then
              if docker compose version >/dev/null 2>&1; then
                docker compose up -d
              elif docker-compose --version >/dev/null 2>&1; then
                docker-compose up -d
              else
                echo "No Docker Compose found"
                exit 1
              fi
            else
              echo "Docker not found"
              exit 1
            fi
          args:
            chdir: "{{ service_dir }}"
          register: start_result


