---
- name: Backup Docker service and upload to OneDrive
  hosts: localhost

  vars:
    base_dir: "/home/karsten"
    backup_base_dir: "{{ base_dir }}/backups"
    service_name: "temp_service"
    service_dir: "{{ base_dir }}/{{ service_name }}"
    backup_dir: "{{ base_dir }}/backups/{{ service_name }}_backups"
    nas_backup_dir: "/mnt/backups/{{ service_name }}"
    rclone_remote: "onedrive:backups/{{ service_name }}_backups"
    backup_pattern: "{{ service_name }}_backup_*.tar.gz"
    compose_file: "{{ service_dir }}/docker-compose.yml"
    timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
    backup_file: "{{ service_name }}_backup_{{ timestamp }}.tar.gz"
    max_local_backups: 1
    max_onedrive_backups: 7
    max_nas_backups: 30
    # Compression settings for better performance
    tar_compression_level: 1  # Fast compression
    parallel_jobs: "{{ ansible_processor_vcpus | default(2) }}"

  tasks:
    - name: Backup Docker service
      include_role:
        name: docker_backup