---
# Backup validation tasks
- name: Validate backup integrity
  hosts: localhost
  vars:
    base_dir: "/home/karsten"
    service_name: "{{ service_name | default('temp_service') }}"
    backup_dir: "{{ base_dir }}/backups/{{ service_name }}_backups"
    backup_file: "{{ backup_file | default('') }}"

  tasks:
    - name: Find latest backup if not specified
      shell: ls -1t {{ backup_dir }}/{{ service_name }}_backup_*.tar.gz | head -1
      register: latest_backup
      when: backup_file == ""

    - name: Set backup file path
      set_fact:
        backup_file: "{{ latest_backup.stdout | basename if backup_file == '' else backup_file }}"

    - name: Test backup archive integrity
      shell: tar -tzf "{{ backup_dir }}/{{ backup_file }}" > /dev/null
      register: integrity_check
      failed_when: integrity_check.rc != 0

    - name: Get backup file size
      stat:
        path: "{{ backup_dir }}/{{ backup_file }}"
      register: backup_stat

    - name: Display backup information
      debug:
        msg: |
          Backup validation successful:
          - File: {{ backup_file }}
          - Size: {{ (backup_stat.stat.size / 1024.0 / 1024.0) | round(2) }} MB
          - Created: {{ backup_stat.stat.mtime | to_datetime }}
          - Archive integrity: OK
