---
# Main tasks for Docker container restore

- name: Prepare restore environment
  include_tasks: find_backup.yml
  vars:
    service_name: "{{ service_name }}"
    backup_base_dir: "{{ backup_base_dir }}"

- name: Prepare restore environment
  include_tasks: prepare_restore.yml

- name: Restore data
  include_tasks: restore_data.yml
