---
- name: Restore jellyfin from latest OneDrive backup
  hosts: localhost
  become: yes

  vars_prompt:
    - name: confirm_restore
      prompt: |
        WARNING: This will DELETE your existing ~/jellyfin directory and replace it with the latest backup from OneDrive.
        Type YES to proceed:
      private: no

  pre_tasks:
    - name: Abort if not confirmed
      fail:
        msg: "Restore cancelled."
      when: confirm_restore != "YES"

  vars:
    jellyfin_dir: /home/karsten/jellyfin
    backup_dir: /home/karsten/jellyfin_backups
    rclone_remote: "onedrive:jellyfin_backups"

  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: karsten
        group: karsten
        mode: '0755'

    - name: Stop jellyfin containers
      become_user: karsten
      shell: docker-compose down
      args:
        chdir: "{{ jellyfin_dir }}"

    - name: Find latest backup on OneDrive
      become_user: karsten
      shell: |
        rclone ls "{{ rclone_remote }}" | awk '{print $2}' | grep '^jellyfin_service_backup_.*\.tar\.gz$' | sort | tail -n 1
      register: latest_backup
      changed_when: false

    - name: Fail if no backup found
      fail:
        msg: "No backups found on OneDrive!"
      when: latest_backup.stdout == ""

    - name: Download latest backup from OneDrive
      become_user: karsten
      shell: |
        rclone copy "{{ rclone_remote }}/{{ latest_backup.stdout }}" "{{ backup_dir }}/"
      args:
        executable: /bin/bash

    - name: Remove existing jellyfin directory
      become: yes
      file:
        path: /home/karsten/jellyfin
        state: absent

    - name: Recreate jellyfin directory
      become_user: karsten
      file:
        path: /home/karsten/jellyfin
        state: directory
        mode: '0755'

    - name: Extract backup archive into ~/jellyfin
      become_user: karsten
      unarchive:
        src: "{{ backup_dir }}/{{ latest_backup.stdout }}"
        dest: "/home/karsten"
        remote_src: no
        extra_opts:
          - --overwrite
          - --no-same-owner
          - --no-same-permissions

    - name: Start jellyfin containers
      become_user: karsten
      shell: docker-compose up -d
      args:
        chdir: "{{ jellyfin_dir }}"
